services:
  portfolio:
    build: .                 # <--- IMPORTANTE: Esto le dice que use tu Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "8081:4173"          # <--- Mapea el 8081 (host) al 4173 (donde corre 'serve')
    # Quité la línea de 'image: nginx' porque chocaba con tu Dockerfile
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
